### PR TITLE
Add installing scripts

### LINKED ISSUE #9: Add docker files

### PR DESCRIPTION
**Pull request by Nircek**
It resolves #9 and will be useful to deploy the first prototype #8.
- [x] Docker
- [x] ~systemd service~
- [x] ~make scripts~ // docker does it all for us
- [x] auto update
- [x] README build instructions

### CODE REVIEW

**Comment by Nircek** [comment]
Read this before making make scripts:
 - https://en.wikipedia.org/wiki/GNU_Autotools
 - https://stackoverflow.com/a/59483634/6732111

**Comment by Nircek** [comment]
As far as I'm concerned, we don't have to write any systemd services because Docker provides us with the [restart policies](https://docs.docker.com/config/containers/start-containers-automatically/), so the one command line should satisfy us.

**Comment by Nircek** [comment]
And the [watchtower](https://github.com/containrrr/watchtower) should auto-update it. Nice.

**Comment by Nircek** [comment]
There is a nice README:
https://github.com/Pikne-Programy/pikne-zadania/blob/installing-scripts/README.md
@miloszwasacz and @MichalTheProgrammer vote for it!

**Comment by Nircek** [comment]
That works. But it doesn't persist any previous logs after an update.

Please don't merge, I will do it.

**Comment by MichalTheProgrammer** [comment]
Very nice README @Nircek!

**Review by MichalTheProgrammer — APPROVED** [review]
Very nice README!

**Pull request merged**
